import { IDatabaseTableLayout } from '.';

/**
 * Interface for a key-value database layout.
 * Example:
 * {
 *   'table1': {
 *     indexes: [
 *       { keyPath: 'key1' },
 *       { keyPath: 'key2' },
 *     ],
 *   },
 * }
 * @category Key-Value Database
 */
export interface IDatabaseLayout {
  /**
   * The tables in the database.
   * The primary key of each table is automatically generated by the database.
   */
  tables: {
    [tableName: string]: IDatabaseTableLayout;
  };
  /**
   * The version of the layout.
   */
  version: number;
}
