/**
 * The AI prompt source Enum
 * @category AI
 */
export enum PromptSource {
  /**
   * The prompt was generated by the AI.
   */
  AI = 'ai',

  /**
   * The prompt was generated by a human.
   */
  Human = 'human'
};
